wget https://raw.githubusercontent.com/skupperproject/skupper-example-prometheus/master/README.md  -O skupper-example.prometheus.md
wget https://raw.githubusercontent.com/skupperproject/skupper-example-http-load-balancing/master/README.md  -O skupper-example.http-load-balancing.md
wget https://raw.githubusercontent.com/skupperproject/skupper-example-postgresql/master/README.md  -O skupper-example.postgresql.md
wget https://raw.githubusercontent.com/skupperproject/skupper-example-bookinfo/master/README.md  -O skupper-example.bookinfo.md
wget https://raw.githubusercontent.com/skupperproject/skupper-example-grpc/master/README.md  -O skupper-example.grpc.md
wget https://raw.githubusercontent.com/skupperproject/skupper-example-tcp-echo/master/README.md  -O skupper-example.tcp-echo.md
wget https://raw.githubusercontent.com/skupperproject/skupper-example-mongodb-replica-set/master/README.md  -O skupper-example.mongodb-replica-set.md
wget https://raw.githubusercontent.com/skupperproject/skupper-example-iperf/master/README.md  -O skupper-example.iperf.md
wget https://raw.githubusercontent.com/skupperproject/skupper-example-trade-zoo/main/README.md -O skupper-example.trade-zoo.md
wget https://raw.githubusercontent.com/skupperproject/skupper-example-hello-world/main/README.md -O skupper-example.hello-world.md
wget https://raw.githubusercontent.com/skupperproject/skupper-example-camel-integration/main/README.md -O skupper-example.camel-integration.md